// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public interface IView {
	/**
	 * 
	 */
	public void updateView();

	/**
	 * 
	 * @param robot 
	 * @param state 
	 */
	public void updateState(String robot, String state);

	/**
	 * 
	 * @param robot 
	 * @param x 
	 * @param y 
	 */
	public void updatePosition(String robot, int x, int y);

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void updateMission(String robot, String mission);
};
