// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public interface IManager {
	/**
	 * 
	 * @param robot 
	 * @param mission 
	 * @param  
	 */
	public void assignMission(String robot, String mission, void null) ;
};
