// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.IManager;
import Model.IMission;
import Model.IRobot;
import java.lang.String;
import java.util.List;

// Manual imports
import java.util.ArrayList;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class Manager implements IManager {
	/**
	 * 
	 */
	private List<IRobot> robots;
	/**
	 * 
	 */
	private List<IMission> missions;

	public Manager(ArrayList<IMission> missions, ArrayList<IRobot> robots) {
		this.robots = robots;
		this.missions = missions;
	}

	/**
	 * 
	 * @param robot 
	 * @return 
	 */
	public IRobot getRobot(String robot) {
		for(int i = 0; i < robots.size(); i++) {
			if(robots.get(i).getName().equals(robot)) {
				return robots.get(i);
			}
		}
		return null;
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public IMission getMission(String mission) {
		for(int i = 0; i < missions.size(); i++) {
			if(missions.get(i).getName().equals(mission)) {
				return missions.get(i);
			}
		}
		return null;
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void assignMission(String robot, String mission) {
		getRobot(robot).setMission(getMission(mission));
	}
};
