// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.IManager;
import Model.IMission;
import Model.IRobot;
import java.lang.String;
import java.util.List;

// Manual imports
import java.util.ArrayList;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class Manager implements IManager {
	/**
	 * 
	 */
	private List<IRobot> robots;
	/**
	 * 
	 */
	private List<IMission> missions;

	/**
	 * 
	 * @param robot 
	 * @return 
	 */
	private IRobot getRobot(String robot) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private IMission getMission(String mission) {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void assignMission(String robot, String mission) {
	}

	/**
	 * 
	 * @return 
	 */
	public List<String> getMissions() {
	}
};
