// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.IManager;
import Model.IMission;
import Model.IRobot;
import Model.Mission;
import Model.Robot;
import java.lang.String;
import java.util.List;

/************************************************************/
/**
 * 
 */
public class Manager implements IManager {
	/**
	 * 
	 */
	public List<Robot> robots;
	/**
	 * 
	 */
	public List<Mission> missions;

	/**
	 * 
	 * @param robot 
	 * @return 
	 */
	public IRobot getRobot(String robot) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public IMission getMission(String mission) {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void assignMission(String robot, String mission) {
	}
};
