// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import java.util.Set;

import Controller.Observer;
import Controller.ViewFactory;
import Model.Environment;
import Model.IRobot;
import project.AbstractRobotSimulator;
import project.AbstractSimulatorMonitor;
import project.RobotAvatar;
import project.SimulatorMonitor;

/************************************************************/
/**
 * 
 */
public class Monitor extends AbstractSimulatorMonitor<RobotAvatar> implements Observer {
	
	/**
	 * 
	 */
	private IRobot robot;
	
	public Monitor(Set<RobotAvatar> robotAvatars, Environment environment) {
		super(robotAvatars, environment);
		
	}
	/**
	 * 
	 */
	private ViewFactory viewfactory;

	/**
	 * 
	 * @param robot 
	 */
	private void updateState(IRobot robot) {
		//this.robot.setState(robot.getState());
	}

	/**
	 * 
	 */
	private void updateView() {
	}

	/**
	 * 
	 * @param robot 
	 */
	private void updatePosition(IRobot robot) {
	}

	/**
	 * 
	 * @param robot 
	 */
	private void updateMission(IRobot robot) {
	}

	/**
	 * 
	 * @param robot 
	 */
	public void update(IRobot robot) {
		
	}


	@Override
	public void update(RobotAvatar arg0) {
		
		
	}


	
};
