// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.INotify;
import Model.IRobot;
import View.IView;

/************************************************************/
/**
 * 
 */
public class Monitor implements INotify {
	/**
	 * 
	 */
	public IView view;
	/**
	 * 
	 */
	public IRobot robot;

	/**
	 * 
	 * @param robot 
	 */
	public void notify(IRobot robot) {
	}

	/**
	 * 
	 * @param robot 
	 */
	private void updateState(IRobot robot) {
	}

	/**
	 * 
	 */
	private void updateView() {
	}

	/**
	 * 
	 * @param robot 
	 */
	private void updatePosition(IRobot robot) {
	}

	/**
	 * 
	 * @param robot 
	 */
	private void updateMission(IRobot robot) {
	}
};
