// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.INotify;
import Model.Adapt;
import Model.IRobot;

/************************************************************/
/**
 * 
 */
public class Navigate implements INotify {
	/**
	 * 
	 */
	public Adapt adapt;
	/**
	 * 
	 */
	public IRobot robot;

	/**
	 * 
	 */
	public void stop() {
	}

	/**
	 * 
	 */
	private void move() {
	}

	/**
	 * 
	 * @param degrees 
	 */
	private void turn(int degrees) {
	}

	/**
	 * 
	 */
	private void forward() {
	}

	/**
	 * 
	 * @param robot 
	 */
	public void notify(IRobot robot) {
	}
};
