// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Controller.Observer;
import Model.Adapt;
import Model.IRobot;

/************************************************************/
/**
 * 
 */
public class Navigate implements Observer {
	/**
	 * 
	 */
	private Adapt adapt;
	/**
	 * 
	 */
	private IRobot robot;

	/**
	 * 
	 */
	public void stop() {
	}

	/**
	 * 
	 */
	private void move() {
	}

	/**
	 * 
	 * @param robot 
	 */
	public void update(IRobot robot) {
	}
};
