// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Model.IRobot;

/************************************************************/
/**
 * 
 */
public interface Observer {
	/**
	 * 
	 * @param robot 
	 */
	public void update(IRobot robot);
	

};
