// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import View.IView;

/************************************************************/
/**
 * 
 */
public class ViewFactory {
	/**
	 * 
	 * @return 
	 */
	public IView getView() {
	}
};
