// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import java.lang.String;

/************************************************************/
/**
 * 
 */
public interface IView {
	/**
	 * 
	 * @param state 
	 * @param  
	 */
	public void updateState(String state, void null) ;

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 * @param  
	 */
	public void updateMission(String robot, String mission, void null) ;

	/**
	 * 
	 * @param robot 
	 * @param x 
	 * @param y 
	 * @param  
	 */
	public void updatePosition(String robot, int x, int y, void null) ;

	/**
	 * 
	 * @param  
	 */
	public void updateView(void null) ;
};
