// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import Controller.IManager;
import View.IView;
import java.lang.String;
import java.util.HashMap;
import java.util.List;

// Manual imports
import project.Point;
// End of manual imports

import java.awt.FlowLayout;

import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextField;

/************************************************************/
/**
 * 
 */
public class OperatorView extends JFrame implements IView {
	/**
	 * 
	 */
	private IManager imanager;
	/**
	 * 
	 */
	private HashMap<String, Point> robots;
	/**
	 * 
	 */
	private HashMap<String, String> activeMissions;
	/**
	 * 
	 */
	public List<String> missions;
	
	public OperatorView() {
		getContentPane().setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
		
		JPanel panel = new JPanel();
		getContentPane().add(panel);
		
		//List of robots -----
		DefaultListModel<String> rList = new DefaultListModel<>();
		for (String robot : robots.keySet()) {
			rList.addElement(robot);
		}
		JList<String> robotList = new JList<>(rList);
		JScrollPane robotScrollPane = new JScrollPane(robotList);
		panel.add(robotScrollPane);
		//---- end of list of robots
		
		//List of missions ----
		DefaultListModel<String> mList = new DefaultListModel<>();
		for (String mission : missions) {
			mList.addElement(mission);
		}
		JList<String> missionList = new JList<>(mList);
		JScrollPane missionScrollPane = new JScrollPane(missionList);
		panel.add(missionScrollPane);
		//---- end of list of missions
		
		JButton assignButton = new JButton("Assign");
		panel.add(assignButton);
		
		initComponents();
	}
	
	/**
	 * 
	 */
	private void initComponents() {
		pack();
		setVisible(true);
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	private void assignMission(String robot, String mission) {
		imanager.assignMission(robot, mission);
	}

	/**
	 * 
	 */
	private void stopEverything() {
		for (String robot : robots.keySet()) {
			imanager.assignMission(robot, "Do nothing");
		}
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void updateMission(String robot, String mission) {
		activeMissions.put(robot, mission);
	}

	/**
	 * 
	 */
	public void updateView() {
	}

	/**
	 * 
	 * @param robot 
	 * @param state 
	 */
	public void updateState(String robot, String state) {
	}

	/**
	 * 
	 * @param robot 
	 * @param point 
	 */
	public void updatePosition(String robot, Point point) {
		robots.put(robot, point);
	}
};
