// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import Controller.IManager;
import View.IView;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import project.Point;

// Manual imports
import project.Point;

// End of manual imports

/************************************************************/
/**
 * 
 */
public class OperatorView implements IView {
	/**
	 * 
	 */
	private IManager imanager;
	/**
	 * 
	 */
	private HashMap<String, Point> robots;
	/**
	 * 
	 */
	private HashMap<String, String> activeMissions;
	/**
	 * 
	 */
	public List<String> missions;

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	private void assignMission(String robot, String mission) {
	}

	/**
	 * 
	 */
	private void stopEverything() {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void updateMission(String robot, String mission) {
	}

	/**
	 * 
	 */
	public void updateView() {
	}

	/**
	 * 
	 * @param robot 
	 * @param state 
	 */
	public void updateState(String robot, String state) {
	}

	/**
	 * 
	 * @param robot 
	 * @param point 
	 */
	public void updatePosition(String robot, Point point) {
	}
};
