// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import Controller.IManager;
import Controller.Manager;
import View.IView;
import java.lang.String;
import java.util.HashMap;

/************************************************************/
/**
 * 
 */
public class View implements IView {
	/**
	 * 
	 */
	public IManager[] imanager;
	/**
	 * 
	 */
	private HashMap<String, Point> robots;
	/**
	 * 
	 */
	private HashMap<String, Point> missions;
	/**
	 * 
	 */
	private Manager manager;

	/**
	 * 
	 */
	public void Operation1() {
	}

	/**
	 * 
	 */
	public void updateState() {
	}

	/**
	 * 
	 * @param state 
	 */
	public void updateState(String state) {
	}

	/**
	 * 
	 */
	public void updateMission() {
	}

	/**
	 * 
	 * @param robot 
	 */
	public void updateMission(String robot) {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void updateMission(String robot, String mission) {
	}

	/**
	 * 
	 */
	public void updatePosition() {
	}

	/**
	 * 
	 * @param robot 
	 */
	public void updatePosition(String robot) {
	}

	/**
	 * 
	 * @param state 
	 * @param  
	 */
	public void updateState(String state, void null) {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 * @param  
	 */
	public void updateMission(String robot, String mission, void null) {
	}

	/**
	 * 
	 * @param robot 
	 * @param x 
	 * @param y 
	 * @param  
	 */
	public void updatePosition(String robot, int x, int y, void null) {
	}

	/**
	 * 
	 */
	public void updateView() {
	}

	/**
	 * 
	 * @param  
	 */
	public void updateView(void null) {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 * @param  
	 */
	private void assignMission(String robot, String mission, void null) {
	}

	/**
	 * 
	 * @param  
	 */
	private void stopEverything(void null) {
	}
};
