// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package View;

import Controller.IManager;
import View.IView;
import java.lang.String;
import java.util.HashMap;

// Manual imports
import java.awt.Point;
import java.util.List;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class View implements IView {
	/**
	 * 
	 */
	public IManager imanager;
	/**
	 * 
	 */
	private HashMap<String, Point> robots;
	/**
	 * 
	 */
	private HashMap<String, List<Point>> missions;

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	private void assignMission(String robot, String mission) {
	}

	/**
	 * 
	 */
	private void stopEverything() {
	}

	/**
	 * 
	 * @param robot 
	 * @param mission 
	 */
	public void updateMission(String robot, String mission) {
	}

	/**
	 * 
	 * @param robot 
	 * @param x 
	 * @param y 
	 */
	public void updatePosition(String robot, int x, int y) {
	}

	/**
	 * 
	 */
	public void updateView() {
	}

	/**
	 * 
	 * @param robot 
	 * @param state 
	 */
	public void updateState(String robot, String state) {
	}
};
