// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Controller;

import Model.IRobot;

/************************************************************/
/**
 * 
 */
public interface INotify {
	/**
	 * 
	 * @param robot 
	 */
	public void notify(IRobot robot);
};
