// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.Mission;
import java.util.List;

// Manual imports
import java.awt.Point;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public List<Point> getStrategy(Mission mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private List<Point> calculateStrategy(Mission mission) {
	}
};
