// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.awt.Point;
import java.lang.String;
import project.LocationController;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	private Point centerPoint;
	/**
	 * 
	 */
	private int radius;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	public LocationController locationcontroller;

	/**
	 * 
	 * @return 
	 */
	public Point getCenterPoint() {
	}

	/**
	 * 
	 * @return 
	 */
	public int getRadius() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}

	/**
	 * 
	 * @return 
	 */
	public LocationController getLocationController() {
	}
};
