// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.lang.String;
import project.LocationController;
import project.Point;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	private Point centerPoint;
	/**
	 * 
	 */
	private int radius;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private LocationController locationController;
	
	private int reward;
	
	public Area(Point centerPoint, int radius, String name, int reward, LocationController locationcontroller) {
		this.centerPoint = centerPoint;
		this.radius = radius;
		this.name = name;
		this.reward = reward;
		this.locationController =  locationcontroller;
	}

	/**
	 * 
	 * @return 
	 */
	public Point getCenterPoint() {
		return centerPoint;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRadius() {
		return radius;
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
		return name;
	}

	/**
	 * 
	 * @return 
	 */
	public LocationController getLocationController() {
		return locationController;
	}
	
	public int getReward() {
		return this.reward;
	}
};