// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.lang.String;
import project.LocationController;
import project.Point;

/************************************************************/
/**
 * 
 */
public class Area {
	/**
	 * 
	 */
	private Point centerPoint;
	/**
	 * 
	 */
	private int radius;
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private LocationController locationcontroller;

	/**
	 * 
	 * @return 
	 */
	public Point getCenterPoint() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public int getRadius() {
		return 0;
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
		return null;
	}

	/**
	 * 
	 * @return 
	 */
	public LocationController getLocationController() {
		return null;
	}
};