// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import java.lang.String;
import java.util.List;

// Manual imports
import project.Point;
// End of manual imports

/************************************************************/
/**
 * 
 */
public interface IMission {
	/**
	 * 
	 * @return 
	 */
	public List<Point> getPoints();

	/**
	 * 
	 * @return 
	 */
	public String getName();
};
