// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.IMission;
import Model.Strategy;
import java.awt.Point;
import java.lang.String;

/************************************************************/
/**
 * 
 */
public interface IRobot {
	/**
	 * 
	 * @return 
	 */
	public String getState();

	/**
	 * 
	 * @return 
	 */
	public IMission getMission();

	/**
	 * 
	 * @return 
	 */
	public Point getPosition();

	/**
	 * 
	 * @return 
	 */
	public Strategy getStrategy();
};
