// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.IMission;
import java.lang.String;
import java.util.List;

// Manual imports
import java.awt.Point;
import java.util.ArrayList;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class Mission implements IMission {
	/**
	 * 
	 */
	private String name;
	/**
	 * 
	 */
	private List<Point> points;

	/**
	 * 
	 * @return 
	 */
	public List<Point> getPoints() {
	}

	/**
	 * 
	 * @return 
	 */
	public String getName() {
	}
};
