// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.IMission;

/************************************************************/
/**
 * 
 */
public class Mission implements IMission {
};
