// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Controller.Observer;

/************************************************************/
/**
 * 
 */
public interface Observable {
	/**
	 * 
	 */
	public void notifyAllObservers();

	/**
	 * 
	 * @param observer 
	 */
	public void attach(Observer observer);
};