// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.Strategy;

/************************************************************/
/**
 * 
 */
public class StopStrategy extends Strategy {
	
	
	public StopStrategy(IMission mission) {
		super(mission);
	}
	/**
	 * 
	 */
	public void isInNewRoom() {
	}

	@Override
	public void isAtDestination() {
		try {
			Thread.sleep(2000);
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
};