// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.Strategy;

/************************************************************/
/**
 * 
 */
public class StopStrategy extends Strategy {
	/**
	 * 
	 */
	public void isInNewRoom() {
	}
};
