// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Model;

import Model.IMission;
import java.util.List;

// Manual imports
import project.Point;
// End of manual imports

/************************************************************/
/**
 * 
 */
public class Strategy {
	/**
	 * 
	 */
	private List<Point> points;

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	public Model.Strategy getStrategy(IMission mission) {
	}

	/**
	 * 
	 * @param mission 
	 * @return 
	 */
	private List<Point> calculateStrategy(IMission mission) {
	}

	/**
	 * 
	 */
	public void isAtDestination() {
	}

	/**
	 * 
	 * @return 
	 */
	public List<Point> getPoints() {
	}

	/**
	 * 
	 */
	public void isInNewRoom() {
	}
};
